# Experiments — Electricity Load Forecasting

## Imports & Setup

In [1]:
import sys
sys.path.append("..") 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
import xgboost as xgb
import lightgbm as lgb
import catboost as cb

from src.experiments import config, data, features, cv, hpo
from src.experiments.mlflow_utils import log_cv_run
from src.inference import feature_engineering as fe

config.init_mlflow()

/teamspace/studios/this_studio/electricity-distribution-forecast/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Load Data & Split

In [2]:
df = data.load_raw_data("../data/interim/df_core_features.parquet")
df = features.add_base_features(df)

df = features.drop_base_feature_warmup(df)

train, test, TRAIN_END, TEST_START = data.chronological_split(df, purge_days=config.PURGE_DAYS)
train, test = features.attach_holiday_names(train, test)



print(f"Train: {len(train):,} rows | {train['timestamp'].min()} -> {train['timestamp'].max()}")
print(f"Test:  {len(test):,} rows | {test['timestamp'].min()} -> {test['timestamp'].max()}")

Dropped 24 warm-up row(s) for ['temp_c_roll_std_72', 'temp_change_vs_lag24']
Train: 83,931 rows | 2016-01-09 00:00:00+00:00 -> 2025-08-06 05:00:00+00:00
Test:  8,587 rows | 2025-08-13 05:00:00+00:00 -> 2026-08-05 23:00:00+00:00

## Baseline: Constant & Persistence

In [3]:
baseline_oof = cv.run_naive_baselines(train, config.FOLD_BOUNDARIES, config.TARGET)
for name, oof in baseline_oof.items():
    m = cv.compute_oof_metrics(train, oof, config.TARGET)
    print(f"{name} OOF RMSE: {m['rmse']:.2f}")

Fold 1  |  Constant RMSE: 1806.95  |  Persistence RMSE: 772.98
Fold 2  |  Constant RMSE: 2331.61  |  Persistence RMSE: 811.14
Fold 3  |  Constant RMSE: 2389.79  |  Persistence RMSE: 804.75
Fold 4  |  Constant RMSE: 2585.27  |  Persistence RMSE: 800.56
Fold 5  |  Constant RMSE: 2592.49  |  Persistence RMSE: 843.63
constant OOF RMSE: 2358.82
persistence OOF RMSE: 806.93

## Linear Regression (raw features)

In [4]:
result_lr = cv.run_raw_cv(
    train, config.FOLD_BOUNDARIES, config.TARGET, config.FEATURES,
    model_builder=LinearRegression, scale_X=True,
)
metrics_lr = cv.compute_oof_metrics(train, result_lr["oof"], config.TARGET)
print(f"Linear Model, CV OOF RMSE: {metrics_lr['rmse']:.2f}  MAPE: {metrics_lr['mape']:.2f}%")

log_cv_run(
    "Baseline_Linear_Regression",
    params={"model_type": "LinearRegression", "features": "raw_features", "cv_strategy": "5-fold-expanding"},
    metrics={"cv_oof_rmse": metrics_lr["rmse"], "cv_oof_mape": metrics_lr["mape"]},
)

Fold 1 RMSE: 740.44
Fold 2 RMSE: 766.35
Fold 3 RMSE: 747.30
Fold 4 RMSE: 761.37
Fold 5 RMSE: 795.27
Linear Model, CV OOF RMSE: 762.38  MAPE: 6.47%
Logged 'Baseline_Linear_Regression' — cv_oof_rmse: 762.38, cv_oof_mape: 6.47
🏃 View run Baseline_Linear_Regression at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2/runs/f21df975e95743e5ac85e56e254d8b1b
🧪 View experiment at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2

## XGBoost (Baseline, raw features)

In [5]:
xgb_baseline_params = dict(n_estimators=500, learning_rate=0.05, max_depth=6, random_state=42, n_jobs=-1)

result_xgb_base = cv.run_raw_cv(
    train, config.FOLD_BOUNDARIES, config.TARGET, config.FEATURES,
    model_builder=lambda: xgb.XGBRegressor(**xgb_baseline_params), scale_X=True,
)
metrics_xgb_base = cv.compute_oof_metrics(train, result_xgb_base["oof"], config.TARGET)
print(f"XGBoost Baseline, CV OOF RMSE: {metrics_xgb_base['rmse']:.2f}  MAPE: {metrics_xgb_base['mape']:.2f}%")

log_cv_run(
    "Baseline_XGBoost_Raw",
    params={"model_type": "XGBoost", "features": "raw_features", "cv_strategy": "5-fold-expanding", **xgb_baseline_params},
    metrics={"cv_oof_rmse": metrics_xgb_base["rmse"], "cv_oof_mape": metrics_xgb_base["mape"]},
)

Fold 1 RMSE: 457.04
Fold 2 RMSE: 618.83
Fold 3 RMSE: 760.06
Fold 4 RMSE: 690.77
Fold 5 RMSE: 683.67
XGBoost Baseline, CV OOF RMSE: 650.27  MAPE: 6.33%
Logged 'Baseline_XGBoost_Raw' — cv_oof_rmse: 650.27, cv_oof_mape: 6.33
🏃 View run Baseline_XGBoost_Raw at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2/runs/08b98e0c63a64693a2eb9c7382238966
🧪 View experiment at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2

## Trend + XGBoost-on-Residual (v1)
Raw features, no derived flags — `fold_feature_fn=None`.

In [6]:
default_gbm_params = dict(n_estimators=500, learning_rate=0.05, max_depth=6, random_state=42, n_jobs=-1)

result_v1 = cv.run_trend_plus_cv(
    train, config.FOLD_BOUNDARIES, config.TARGET, config.FEATURES,
    model_builder=lambda: xgb.XGBRegressor(**default_gbm_params),
    fold_feature_fn=None,
)
metrics_v1 = cv.compute_oof_metrics(train, result_v1["oof"], config.TARGET)
print(f"Trend + XGB (v1), CV OOF RMSE: {metrics_v1['rmse']:.2f}  MAPE: {metrics_v1['mape']:.2f}%")

log_cv_run(
    "Trend_XGB_v1",
    params={"model_type": "Trend+XGBoost", "experiment_version": "v1", "features": "raw_features + trend_idx",
            "cv_strategy": "5-fold-expanding", **default_gbm_params},
    metrics={"cv_oof_rmse": metrics_v1["rmse"], "cv_oof_mape": metrics_v1["mape"]},
)

Fold 1 RMSE: 410.30
Fold 2 RMSE: 419.62
Fold 3 RMSE: 436.16
Fold 4 RMSE: 466.92
Fold 5 RMSE: 412.67
Trend + XGB (v1), CV OOF RMSE: 429.67  MAPE: 3.67%
Logged 'Trend_XGB_v1' — cv_oof_rmse: 429.67, cv_oof_mape: 3.67
🏃 View run Trend_XGB_v1 at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2/runs/cafad7995a654d3f98e4466e9e11d53a
🧪 View experiment at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2

## Trend + XGBoost + Extreme-Event Features (v2)
Same extreme-event fold features as v3 below — only the *feature set passed to the model* differs (`FEATURES_V2` excludes `temp_change_vs_lag24` / `is_high_precip_event`).

In [7]:
result_v2 = cv.run_trend_plus_cv(
    train, config.FOLD_BOUNDARIES, config.TARGET, config.FEATURES_V2,
    model_builder=lambda: xgb.XGBRegressor(**default_gbm_params),
    fold_feature_fn=features.extreme_event_fold_features,
)
metrics_v2 = cv.compute_oof_metrics(train, result_v2["oof"], config.TARGET)
print(f"Trend + XGB + extreme events (v2), CV OOF RMSE: {metrics_v2['rmse']:.2f}  (v1: {metrics_v1['rmse']:.2f})")

log_cv_run(
    "Trend_XGB_v2",
    params={"model_type": "Trend+XGBoost", "experiment_version": "v2",
            "features": "FEATURES_V2 (extreme events + holiday interaction)",
            "cv_strategy": "5-fold-expanding", "extreme_heat_quantile": 0.95, "extreme_cold_quantile": 0.05,
            **default_gbm_params},
    metrics={"cv_oof_rmse": metrics_v2["rmse"], "cv_oof_mape": metrics_v2["mape"]},
)

Fold 1 RMSE: 411.39
Fold 2 RMSE: 421.60
Fold 3 RMSE: 417.61
Fold 4 RMSE: 467.94
Fold 5 RMSE: 403.08
Trend + XGB + extreme events (v2), CV OOF RMSE: 424.96  (v1: 429.67)
Logged 'Trend_XGB_v2' — cv_oof_rmse: 424.96, cv_oof_mape: 3.65
🏃 View run Trend_XGB_v2 at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2/runs/7a249d2350a142a69e8f845c02bab207
🧪 View experiment at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2

## Model Sweep on v3 Features (XGBoost / LightGBM / CatBoost / KNN)
This replaces four separate copy-pasted cells — same CV runner, only the model builder changes.

In [8]:
v3_fold_features = features.extreme_event_fold_features

model_configs = {
    "xgb_v3":      dict(builder=lambda: xgb.XGBRegressor(**default_gbm_params), scale_X=False,
                         mlflow_name="Trend_XGB_v3", model_label="Trend+XGBoost",
                         hp=default_gbm_params),
    "lgbm_v3":     dict(builder=lambda: lgb.LGBMRegressor(**default_gbm_params, verbosity=-1), scale_X=False,
                         mlflow_name="Trend_LightGBM_v3", model_label="Trend+LightGBM",
                         hp=default_gbm_params),
    "catboost_v3": dict(builder=lambda: cb.CatBoostRegressor(
                             iterations=500, learning_rate=0.05, depth=6,
                             random_state=42, thread_count=-1, verbose=0), scale_X=False,
                         mlflow_name="Trend_CatBoost_v3", model_label="Trend+CatBoost",
                         hp=dict(iterations=500, learning_rate=0.05, depth=6)),
    "knn_v3":      dict(builder=lambda: KNeighborsRegressor(n_neighbors=15, weights="distance", n_jobs=-1), scale_X=True,
                         mlflow_name="Trend_KNN_v3", model_label="Trend+KNN",
                         hp=dict(n_neighbors=15, weights="distance")),
}

v3_results, v3_metrics = {}, {}
for name, cfg in model_configs.items():
    print(f"--- {name} ---")
    result = cv.run_trend_plus_cv(
        train, config.FOLD_BOUNDARIES, config.TARGET, config.FEATURES_V3,
        model_builder=cfg["builder"], fold_feature_fn=v3_fold_features, scale_X=cfg["scale_X"],
    )
    m = cv.compute_oof_metrics(train, result["oof"], config.TARGET)
    v3_results[name] = result
    v3_metrics[name] = m
    print(f"{cfg['model_label']} (v3), CV OOF RMSE: {m['rmse']:.2f}  MAPE: {m['mape']:.2f}%\n")

    log_cv_run(
        cfg["mlflow_name"],
        params={"model_type": cfg["model_label"], "experiment_version": "v3",
                "features": "FEATURES_V3", "cv_strategy": "5-fold-expanding", **cfg["hp"]},
        metrics={"cv_oof_rmse": m["rmse"], "cv_oof_mape": m["mape"]},
    )

--- xgb_v3 ---
Fold 1 RMSE: 407.80
Fold 2 RMSE: 380.97
Fold 3 RMSE: 386.74
Fold 4 RMSE: 446.89
Fold 5 RMSE: 379.67
Trend+XGBoost (v3), CV OOF RMSE: 401.24  MAPE: 3.48%

Logged 'Trend_XGB_v3' — cv_oof_rmse: 401.24, cv_oof_mape: 3.48
🏃 View run Trend_XGB_v3 at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2/runs/5ffa63eb54c74b5e99799208b0055be7
🧪 View experiment at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2
--- lgbm_v3 ---
Fold 1 RMSE: 404.51
Fold 2 RMSE: 386.38
Fold 3 RMSE: 390.29
Fold 4 RMSE: 429.65
Fold 5 RMSE: 384.63
Trend+LightGBM (v3), CV OOF RMSE: 399.46  MAPE: 3.48%

Logged 'Trend_LightGBM_v3' — cv_oof_rmse: 399.46, cv_oof_mape: 3.48
🏃 View run Trend_LightGBM_v3 at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2/runs/ca8857381d0f4494b98bc1bf8e48195f
🧪 View experiment at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2
--- catboost_v3 ---
Fold 1 RMSE: 398.15
Fold 2 RMSE: 364.57
Fold 3 RMSE: 385.10
Fold 4 RMSE: 438.97
Fold 5 RMSE: 380.42
Trend+CatBoost (v3), CV OOF RMSE: 394.27  MAPE: 3.46%

Logged 'Trend_CatBoost_v3' — cv_oof_rmse: 394.27, cv_oof_mape: 3.46
🏃 View run Trend_CatBoost_v3 at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2/runs/16372c24ddb94c5698cf5f367a1a211d
🧪 View experiment at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2
--- knn_v3 ---
Fold 1 RMSE: 545.99
Fold 2 RMSE: 502.95
Fold 3 RMSE: 535.28
Fold 4 RMSE: 615.72
Fold 5 RMSE: 578.02
Trend+KNN (v3), CV OOF RMSE: 556.95  MAPE: 5.16%

Logged 'Trend_KNN_v3' — cv_oof_rmse: 556.95, cv_oof_mape: 5.16
🏃 View run Trend_KNN_v3 at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2/runs/88b6ec150edf450985566beb14e65ef5
🧪 View experiment at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2

## Model Comparison — RMSE / MAPE / Peak-MAPE

In [9]:
oof_dict_v3 = {name: v3_results[name]["oof"] for name in model_configs}
oof_dict_v3["lr"] = result_lr["oof"]  # note: lr ran on raw FEATURES, not v3 — included for reference only

model_rows = []
for name, oof in oof_dict_v3.items():
    valid = ~np.isnan(oof)
    y_true, y_pred = train.loc[valid, config.TARGET], oof[valid]
    m = cv.compute_metrics(y_true.to_numpy(), y_pred)
    model_rows.append({"model": name, **m})

model_comparison = pd.DataFrame(model_rows).sort_values("peak_mape").reset_index(drop=True)
model_comparison

         model        rmse      mape  peak_mape
0      lgbm_v3  399.462778  3.482224   4.023537
1  catboost_v3  394.272088  3.457084   4.031536
2       xgb_v3  401.242833  3.480206   4.076747
3       knn_v3  556.953316  5.162665   4.312551
4           lr  762.381695  6.468634   5.757238

## Residual Correlation Check

In [10]:
common_valid = np.ones(len(train), dtype=bool)
for oof in oof_dict_v3.values():
    common_valid &= ~np.isnan(oof)

resid_df = pd.DataFrame({
    name: (train[config.TARGET].values - oof)[common_valid]
    for name, oof in oof_dict_v3.items()
})
print(f"Rows compared: {common_valid.sum():,}")
resid_df.corr()

Rows compared: 43,824

               xgb_v3   lgbm_v3  catboost_v3    knn_v3        lr
xgb_v3       1.000000  0.963335     0.910203  0.636221  0.438522
lgbm_v3      0.963335  1.000000     0.923620  0.649987  0.446224
catboost_v3  0.910203  0.923620     1.000000  0.697187  0.486682
knn_v3       0.636221  0.649987     0.697187  1.000000  0.474338
lr           0.438522  0.446224     0.486682  0.474338  1.000000

## Hill-Climbing Ensemble

In [11]:
y_true_full = train[config.TARGET].values
ensemble_preds, selected, ensemble_weights, ensemble_history, solo_rmse = cv.hill_climb_ensemble(
    oof_dict_v3, y_true_full, common_valid
)

print("Solo RMSE (on common_valid rows):")
for name, rmse in sorted(solo_rmse.items(), key=lambda x: x[1]):
    print(f"  {name}: {rmse:.2f}")

print(f"\nHill-climb ensemble OOF RMSE: {ensemble_history[-1]:.2f}")
print("\nModel weights (by selection frequency):")
print(ensemble_weights)

Solo RMSE (on common_valid rows):
  catboost_v3: 394.27
  lgbm_v3: 399.46
  xgb_v3: 401.24
  knn_v3: 556.95
  lr: 762.38

Hill-climb ensemble OOF RMSE: 387.67

Model weights (by selection frequency):
catboost_v3    0.50
xgb_v3         0.25
lgbm_v3        0.25
Name: proportion, dtype: float64

## Hyperparameter Tuning — XGBoost / LightGBM / CatBoost (Optuna)
Each `run_study` call replaces a separate hand-written objective + CV loop — same shared `oof_rmse_for_model` harness underneath for all three.

In [12]:
studies = {}
for model_name in ("xgb", "lgbm", "catboost"):
    baseline_rmse = v3_metrics[f"{model_name}_v3"]["rmse"]
    study = hpo.run_study(
        model_name, train, config.FOLD_BOUNDARIES, config.TARGET, config.FEATURES_V3,
        fold_feature_fn=v3_fold_features, n_trials=40,
    )
    studies[model_name] = study
    print(f"Best {model_name} OOF RMSE: {study.best_value:.2f}  (default-params baseline: {baseline_rmse:.2f})")
    print(study.best_params)

[I 2026-08-17 19:10:20,062] A new study created in memory with name: xgb_v3_tuning
Best trial: 0. Best value: 394.609:   2%|▎         | 1/40 [00:10<07:03, 10.85s/it]

[I 2026-08-17 19:10:30,913] Trial 0 finished with value: 394.6093652418304 and parameters: {'n_estimators': 490, 'learning_rate': 0.05403728444411373, 'max_depth': 6, 'min_child_weight': 19, 'subsample': 0.608555781758256, 'colsample_bytree': 0.7260646491894605, 'reg_alpha': 0.03834043792723947, 'reg_lambda': 0.0023333714604885257}. Best is trial 0 with value: 394.6093652418304.

Best trial: 0. Best value: 394.609:   5%|▌         | 2/40 [00:18<05:43,  9.03s/it]

[I 2026-08-17 19:10:38,671] Trial 1 finished with value: 396.5627282057018 and parameters: {'n_estimators': 513, 'learning_rate': 0.05867041879152246, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.9631249119204198, 'colsample_bytree': 0.7160162483498188, 'reg_alpha': 0.003999274070660997, 'reg_lambda': 0.22042508392192087}. Best is trial 0 with value: 394.6093652418304.

Best trial: 0. Best value: 394.609:   8%|▊         | 3/40 [00:39<08:52, 14.38s/it]

[I 2026-08-17 19:10:59,415] Trial 2 finished with value: 420.4361432507693 and parameters: {'n_estimators': 228, 'learning_rate': 0.01659612239618496, 'max_depth': 10, 'min_child_weight': 3, 'subsample': 0.9045787074076755, 'colsample_bytree': 0.7900367956942712, 'reg_alpha': 4.33043244637627, 'reg_lambda': 0.4510461711661554}. Best is trial 0 with value: 394.6093652418304.

Best trial: 0. Best value: 394.609:  10%|█         | 4/40 [00:53<08:35, 14.32s/it]

[I 2026-08-17 19:11:13,639] Trial 3 finished with value: 409.77496979197434 and parameters: {'n_estimators': 339, 'learning_rate': 0.09937378769275072, 'max_depth': 9, 'min_child_weight': 15, 'subsample': 0.6122881833058934, 'colsample_bytree': 0.8985167915441078, 'reg_alpha': 0.040097560745474395, 'reg_lambda': 0.3416615934731094}. Best is trial 0 with value: 394.6093652418304.

Best trial: 0. Best value: 394.609:  12%|█▎        | 5/40 [00:56<06:01, 10.32s/it]

[I 2026-08-17 19:11:16,872] Trial 4 finished with value: 406.4747952421589 and parameters: {'n_estimators': 263, 'learning_rate': 0.13806012349481317, 'max_depth': 3, 'min_child_weight': 15, 'subsample': 0.6122626752118351, 'colsample_bytree': 0.750814823994786, 'reg_alpha': 0.010715260775862436, 'reg_lambda': 0.11311498171533589}. Best is trial 0 with value: 394.6093652418304.

Best trial: 0. Best value: 394.609:  15%|█▌        | 6/40 [01:08<06:07, 10.79s/it]

[I 2026-08-17 19:11:28,585] Trial 5 finished with value: 407.8158966300446 and parameters: {'n_estimators': 786, 'learning_rate': 0.13259388533219388, 'max_depth': 5, 'min_child_weight': 12, 'subsample': 0.8460795641283709, 'colsample_bytree': 0.8556568305114451, 'reg_alpha': 3.446779531335892, 'reg_lambda': 0.0012476481983135985}. Best is trial 0 with value: 394.6093652418304.

Best trial: 0. Best value: 394.609:  18%|█▊        | 7/40 [01:24<06:54, 12.55s/it]

[I 2026-08-17 19:11:44,754] Trial 6 finished with value: 414.6168844475089 and parameters: {'n_estimators': 382, 'learning_rate': 0.09690927549238276, 'max_depth': 10, 'min_child_weight': 16, 'subsample': 0.9461314722262766, 'colsample_bytree': 0.6829751453701116, 'reg_alpha': 0.8871314891368831, 'reg_lambda': 0.04021248387440214}. Best is trial 0 with value: 394.6093652418304.

Best trial: 0. Best value: 394.609:  20%|██        | 8/40 [01:28<05:11,  9.75s/it]

[I 2026-08-17 19:11:48,503] Trial 7 finished with value: 406.2279306180636 and parameters: {'n_estimators': 329, 'learning_rate': 0.10535756507057262, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.8033639588888706, 'colsample_bytree': 0.7071634253852724, 'reg_alpha': 0.19187895870596788, 'reg_lambda': 7.381302114233239}. Best is trial 0 with value: 394.6093652418304.

Best trial: 0. Best value: 394.609:  22%|██▎       | 9/40 [01:40<05:23, 10.43s/it]

[I 2026-08-17 19:12:00,413] Trial 8 finished with value: 406.5208234271992 and parameters: {'n_estimators': 410, 'learning_rate': 0.09279499161333844, 'max_depth': 7, 'min_child_weight': 7, 'subsample': 0.8456765325457045, 'colsample_bytree': 0.9367215370338576, 'reg_alpha': 0.00283768289333436, 'reg_lambda': 2.3455310248968706}. Best is trial 0 with value: 394.6093652418304.

Best trial: 0. Best value: 394.609:  25%|██▌       | 10/40 [01:57<06:12, 12.43s/it]

[I 2026-08-17 19:12:17,343] Trial 9 finished with value: 396.85469701797285 and parameters: {'n_estimators': 531, 'learning_rate': 0.03707987766583404, 'max_depth': 8, 'min_child_weight': 10, 'subsample': 0.8976073931938449, 'colsample_bytree': 0.6704947859912664, 'reg_alpha': 0.08652106237724759, 'reg_lambda': 0.061890105500839704}. Best is trial 0 with value: 394.6093652418304.

Best trial: 10. Best value: 393.937:  28%|██▊       | 11/40 [02:12<06:24, 13.26s/it]

[I 2026-08-17 19:12:32,471] Trial 10 finished with value: 393.9367697514509 and parameters: {'n_estimators': 762, 'learning_rate': 0.014173210975372472, 'max_depth': 6, 'min_child_weight': 20, 'subsample': 0.7126385642830412, 'colsample_bytree': 0.6135022058894445, 'reg_alpha': 0.0010085960571037235, 'reg_lambda': 0.002833918147716972}. Best is trial 10 with value: 393.9367697514509.

Best trial: 10. Best value: 393.937:  30%|███       | 12/40 [02:27<06:29, 13.92s/it]

[I 2026-08-17 19:12:47,912] Trial 11 finished with value: 396.10807221153584 and parameters: {'n_estimators': 797, 'learning_rate': 0.012051019350159602, 'max_depth': 6, 'min_child_weight': 20, 'subsample': 0.703462097825854, 'colsample_bytree': 0.6008535790755807, 'reg_alpha': 0.0013710715321399354, 'reg_lambda': 0.0018231348748297986}. Best is trial 10 with value: 393.9367697514509.

Best trial: 12. Best value: 391.658:  32%|███▎      | 13/40 [02:40<06:04, 13.49s/it]

[I 2026-08-17 19:13:00,399] Trial 12 finished with value: 391.65833214234584 and parameters: {'n_estimators': 659, 'learning_rate': 0.025651243540534042, 'max_depth': 6, 'min_child_weight': 20, 'subsample': 0.6795323203846354, 'colsample_bytree': 0.6006485826307252, 'reg_alpha': 0.013953223221208944, 'reg_lambda': 0.007107142982240935}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  35%|███▌      | 14/40 [02:50<05:26, 12.57s/it]

[I 2026-08-17 19:13:10,858] Trial 13 finished with value: 398.28017614840513 and parameters: {'n_estimators': 671, 'learning_rate': 0.01939527533865093, 'max_depth': 5, 'min_child_weight': 18, 'subsample': 0.717623387632138, 'colsample_bytree': 0.6097997505921369, 'reg_alpha': 0.010378473419080625, 'reg_lambda': 0.011082024679105748}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  38%|███▊      | 15/40 [03:06<05:39, 13.58s/it]

[I 2026-08-17 19:13:26,788] Trial 14 finished with value: 392.75483803001936 and parameters: {'n_estimators': 677, 'learning_rate': 0.026282272427217934, 'max_depth': 7, 'min_child_weight': 20, 'subsample': 0.7270761495759018, 'colsample_bytree': 0.6347892652385194, 'reg_alpha': 0.001061924642487555, 'reg_lambda': 0.009055680859168856}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  40%|████      | 16/40 [03:26<06:11, 15.46s/it]

[I 2026-08-17 19:13:46,601] Trial 15 finished with value: 394.66438679153225 and parameters: {'n_estimators': 648, 'learning_rate': 0.025544946303170862, 'max_depth': 8, 'min_child_weight': 17, 'subsample': 0.7573259180456592, 'colsample_bytree': 0.6588747895237826, 'reg_alpha': 0.009133982457248191, 'reg_lambda': 0.009241315283606012}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  42%|████▎     | 17/40 [03:41<05:50, 15.26s/it]

[I 2026-08-17 19:14:01,395] Trial 16 finished with value: 392.3586754823266 and parameters: {'n_estimators': 618, 'learning_rate': 0.02876182402535943, 'max_depth': 7, 'min_child_weight': 14, 'subsample': 0.6670170814318779, 'colsample_bytree': 0.646909868485642, 'reg_alpha': 0.0037575695200404947, 'reg_lambda': 0.01172911855498647}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  45%|████▌     | 18/40 [03:49<04:50, 13.21s/it]

[I 2026-08-17 19:14:09,827] Trial 17 finished with value: 400.0789668146501 and parameters: {'n_estimators': 595, 'learning_rate': 0.03524741518544162, 'max_depth': 4, 'min_child_weight': 12, 'subsample': 0.6525829474930415, 'colsample_bytree': 0.7957074567876002, 'reg_alpha': 0.2988550196969589, 'reg_lambda': 0.028477999692045577}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  48%|████▊     | 19/40 [04:04<04:46, 13.65s/it]

[I 2026-08-17 19:14:24,502] Trial 18 finished with value: 395.44606383836924 and parameters: {'n_estimators': 591, 'learning_rate': 0.04648277871832503, 'max_depth': 7, 'min_child_weight': 13, 'subsample': 0.6725945763140202, 'colsample_bytree': 0.6503109077338531, 'reg_alpha': 0.023167486832204157, 'reg_lambda': 0.005565991999428293}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  50%|█████     | 20/40 [05:22<11:01, 33.10s/it]

[I 2026-08-17 19:15:42,928] Trial 19 finished with value: 395.16793157748947 and parameters: {'n_estimators': 720, 'learning_rate': 0.023489624368958458, 'max_depth': 8, 'min_child_weight': 8, 'subsample': 0.7839877054448482, 'colsample_bytree': 0.7646498277468323, 'reg_alpha': 0.00423843769183704, 'reg_lambda': 0.03216907241840224}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  52%|█████▎    | 21/40 [06:40<14:43, 46.50s/it]

[I 2026-08-17 19:17:00,677] Trial 20 finished with value: 395.96033612252336 and parameters: {'n_estimators': 590, 'learning_rate': 0.01030163620141551, 'max_depth': 9, 'min_child_weight': 14, 'subsample': 0.6629620677590751, 'colsample_bytree': 0.6844735400410596, 'reg_alpha': 0.022325761975736394, 'reg_lambda': 0.017945107779688132}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  55%|█████▌    | 22/40 [06:59<11:27, 38.20s/it]

[I 2026-08-17 19:17:19,510] Trial 21 finished with value: 393.0093679321357 and parameters: {'n_estimators': 686, 'learning_rate': 0.02972389768252389, 'max_depth': 7, 'min_child_weight': 18, 'subsample': 0.7552204561416851, 'colsample_bytree': 0.6473293519672552, 'reg_alpha': 0.0021966900469639556, 'reg_lambda': 0.0052958011503728905}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  57%|█████▊    | 23/40 [07:18<09:10, 32.39s/it]

[I 2026-08-17 19:17:38,351] Trial 22 finished with value: 391.6663216247281 and parameters: {'n_estimators': 632, 'learning_rate': 0.020381697058824554, 'max_depth': 7, 'min_child_weight': 17, 'subsample': 0.6811991154898361, 'colsample_bytree': 0.6308883088522576, 'reg_alpha': 0.00551862255548916, 'reg_lambda': 0.004755257062898295}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  60%|██████    | 24/40 [07:32<07:12, 27.03s/it]

[I 2026-08-17 19:17:52,896] Trial 23 finished with value: 392.2433325537608 and parameters: {'n_estimators': 623, 'learning_rate': 0.020928307566364452, 'max_depth': 6, 'min_child_weight': 17, 'subsample': 0.6506321769028305, 'colsample_bytree': 0.6000852750095147, 'reg_alpha': 0.008527786389236711, 'reg_lambda': 0.0036577556578871904}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  62%|██████▎   | 25/40 [07:49<05:58, 23.93s/it]

[I 2026-08-17 19:18:09,568] Trial 24 finished with value: 392.02334273153485 and parameters: {'n_estimators': 730, 'learning_rate': 0.017925434184996304, 'max_depth': 6, 'min_child_weight': 18, 'subsample': 0.6387491546447537, 'colsample_bytree': 0.6065005446132229, 'reg_alpha': 0.010824650766786776, 'reg_lambda': 0.0037188783105169417}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  65%|██████▌   | 26/40 [08:01<04:44, 20.33s/it]

[I 2026-08-17 19:18:21,517] Trial 25 finished with value: 417.404675503494 and parameters: {'n_estimators': 729, 'learning_rate': 0.01661993005767689, 'max_depth': 4, 'min_child_weight': 18, 'subsample': 0.6818708079061179, 'colsample_bytree': 0.9956892681293614, 'reg_alpha': 0.09374272580574537, 'reg_lambda': 0.0013730863122170687}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  68%|██████▊   | 27/40 [08:15<04:00, 18.47s/it]

[I 2026-08-17 19:18:35,658] Trial 26 finished with value: 398.4537623340867 and parameters: {'n_estimators': 729, 'learning_rate': 0.01701486410008942, 'max_depth': 5, 'min_child_weight': 16, 'subsample': 0.636076522293866, 'colsample_bytree': 0.6281516460065001, 'reg_alpha': 0.01675954473987176, 'reg_lambda': 0.00596747417183476}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  70%|███████   | 28/40 [08:29<03:24, 17.03s/it]

[I 2026-08-17 19:18:49,314] Trial 27 finished with value: 403.6645218860854 and parameters: {'n_estimators': 558, 'learning_rate': 0.012944936980177938, 'max_depth': 6, 'min_child_weight': 19, 'subsample': 0.7449058858923356, 'colsample_bytree': 0.6869324291899228, 'reg_alpha': 0.061436812278866694, 'reg_lambda': 0.01957310637941196}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  72%|███████▎  | 29/40 [08:36<02:34, 14.06s/it]

[I 2026-08-17 19:18:56,451] Trial 28 finished with value: 404.490688659605 and parameters: {'n_estimators': 442, 'learning_rate': 0.0364480550221308, 'max_depth': 4, 'min_child_weight': 17, 'subsample': 0.6885207262271046, 'colsample_bytree': 0.6279613513273409, 'reg_alpha': 0.006241053428827605, 'reg_lambda': 0.0010721923677039212}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  75%|███████▌  | 30/40 [08:59<02:47, 16.76s/it]

[I 2026-08-17 19:19:19,509] Trial 29 finished with value: 400.99997971427183 and parameters: {'n_estimators': 700, 'learning_rate': 0.04970401674469019, 'max_depth': 8, 'min_child_weight': 20, 'subsample': 0.6044515345521178, 'colsample_bytree': 0.7111648086741991, 'reg_alpha': 0.040676371595474284, 'reg_lambda': 0.0030253006236039422}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  78%|███████▊  | 31/40 [09:11<02:18, 15.35s/it]

[I 2026-08-17 19:19:31,567] Trial 30 finished with value: 395.8794617137695 and parameters: {'n_estimators': 478, 'learning_rate': 0.020455868677801012, 'max_depth': 6, 'min_child_weight': 19, 'subsample': 0.6214488635105027, 'colsample_bytree': 0.7385373143483888, 'reg_alpha': 0.02008090425295056, 'reg_lambda': 0.08773810991354528}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  80%|████████  | 32/40 [09:26<02:01, 15.20s/it]

[I 2026-08-17 19:19:46,416] Trial 31 finished with value: 392.04691782154237 and parameters: {'n_estimators': 638, 'learning_rate': 0.021562672159523302, 'max_depth': 6, 'min_child_weight': 17, 'subsample': 0.6424585485205803, 'colsample_bytree': 0.6025774428805634, 'reg_alpha': 0.007491996237764238, 'reg_lambda': 0.002586139244869862}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  82%|████████▎ | 33/40 [09:37<01:37, 13.95s/it]

[I 2026-08-17 19:19:57,458] Trial 32 finished with value: 399.3784250665524 and parameters: {'n_estimators': 557, 'learning_rate': 0.022723477923757247, 'max_depth': 5, 'min_child_weight': 16, 'subsample': 0.6345045609663371, 'colsample_bytree': 0.6241158991023549, 'reg_alpha': 0.005713954623143971, 'reg_lambda': 0.0028070123683360064}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  85%|████████▌ | 34/40 [09:52<01:26, 14.38s/it]

[I 2026-08-17 19:20:12,849] Trial 33 finished with value: 393.92853589080875 and parameters: {'n_estimators': 644, 'learning_rate': 0.017314242233637252, 'max_depth': 6, 'min_child_weight': 18, 'subsample': 0.688645763362218, 'colsample_bytree': 0.6588124289167379, 'reg_alpha': 0.0020771515377529587, 'reg_lambda': 0.005367438162763759}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  88%|████████▊ | 35/40 [10:12<01:19, 16.00s/it]

[I 2026-08-17 19:20:32,620] Trial 34 finished with value: 393.08881426675794 and parameters: {'n_estimators': 757, 'learning_rate': 0.030777890083475517, 'max_depth': 7, 'min_child_weight': 15, 'subsample': 0.641925927001236, 'colsample_bytree': 0.6236695510086029, 'reg_alpha': 0.015960584249616754, 'reg_lambda': 0.002271480324644171}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  90%|█████████ | 36/40 [10:24<00:58, 14.64s/it]

[I 2026-08-17 19:20:44,094] Trial 35 finished with value: 397.17139806923876 and parameters: {'n_estimators': 641, 'learning_rate': 0.06489336591952176, 'max_depth': 5, 'min_child_weight': 19, 'subsample': 0.6028159090447094, 'colsample_bytree': 0.6694064117003811, 'reg_alpha': 0.038327651257286266, 'reg_lambda': 0.015165927309499911}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  92%|█████████▎| 37/40 [10:36<00:42, 14.07s/it]

[I 2026-08-17 19:20:56,821] Trial 36 finished with value: 398.3684593093589 and parameters: {'n_estimators': 561, 'learning_rate': 0.015440442271897859, 'max_depth': 6, 'min_child_weight': 17, 'subsample': 0.7328630727585239, 'colsample_bytree': 0.6947227047925811, 'reg_alpha': 0.006120407443978492, 'reg_lambda': 0.004388805552385359}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  95%|█████████▌| 38/40 [10:59<00:33, 16.71s/it]

[I 2026-08-17 19:21:19,708] Trial 37 finished with value: 392.93047126690806 and parameters: {'n_estimators': 496, 'learning_rate': 0.018907826507068185, 'max_depth': 9, 'min_child_weight': 15, 'subsample': 0.6978798079423453, 'colsample_bytree': 0.600955437639491, 'reg_alpha': 0.01309800008346301, 'reg_lambda': 0.0017941221292498116}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658:  98%|█████████▊| 39/40 [11:14<00:16, 16.21s/it]

[I 2026-08-17 19:21:34,733] Trial 38 finished with value: 412.36756087382184 and parameters: {'n_estimators': 749, 'learning_rate': 0.010912592270314776, 'max_depth': 5, 'min_child_weight': 16, 'subsample': 0.6214322680675064, 'colsample_bytree': 0.6388404174733997, 'reg_alpha': 0.02898208160432988, 'reg_lambda': 0.819949295282505}. Best is trial 12 with value: 391.65833214234584.

Best trial: 12. Best value: 391.658: 100%|██████████| 40/40 [11:34<00:00, 17.37s/it]
[I 2026-08-17 19:21:54,976] A new study created in memory with name: lgbm_v3_tuning

[I 2026-08-17 19:21:54,971] Trial 39 finished with value: 392.40711416376615 and parameters: {'n_estimators': 709, 'learning_rate': 0.013843616977311254, 'max_depth': 7, 'min_child_weight': 12, 'subsample': 0.6607907536329528, 'colsample_bytree': 0.6669924103597213, 'reg_alpha': 0.0034767869730203647, 'reg_lambda': 0.0010264392101474022}. Best is trial 12 with value: 391.65833214234584.
Best xgb OOF RMSE: 391.66  (default-params baseline: 401.24)
{'n_estimators': 659, 'learning_rate': 0.025651243540534042, 'max_depth': 6, 'min_child_weight': 20, 'subsample': 0.6795323203846354, 'colsample_bytree': 0.6006485826307252, 'reg_alpha': 0.013953223221208944, 'reg_lambda': 0.007107142982240935}

Best trial: 0. Best value: 409.296:   2%|▎         | 1/40 [00:03<02:31,  3.89s/it]

[I 2026-08-17 19:21:58,860] Trial 0 finished with value: 409.2962537592816 and parameters: {'n_estimators': 382, 'learning_rate': 0.07757123815071688, 'num_leaves': 70, 'max_depth': 3, 'min_child_samples': 97, 'subsample': 0.7037419379418434, 'colsample_bytree': 0.7418920008318673, 'reg_alpha': 0.0153496921236925, 'reg_lambda': 1.7837405841780336}. Best is trial 0 with value: 409.2962537592816.

Best trial: 1. Best value: 399.683:   5%|▌         | 2/40 [00:14<05:04,  8.03s/it]

[I 2026-08-17 19:22:09,784] Trial 1 finished with value: 399.6834283441215 and parameters: {'n_estimators': 341, 'learning_rate': 0.030050908360306574, 'num_leaves': 55, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.9210028653401962, 'colsample_bytree': 0.9316324312186346, 'reg_alpha': 0.015431069465013363, 'reg_lambda': 0.5772940410368802}. Best is trial 1 with value: 399.6834283441215.

Best trial: 1. Best value: 399.683:   8%|▊         | 3/40 [00:19<04:00,  6.50s/it]

[I 2026-08-17 19:22:14,461] Trial 2 finished with value: 442.5585730724966 and parameters: {'n_estimators': 451, 'learning_rate': 0.02600072722492945, 'num_leaves': 39, 'max_depth': 3, 'min_child_samples': 64, 'subsample': 0.9323633525056747, 'colsample_bytree': 0.7940878095716069, 'reg_alpha': 8.866066766183616, 'reg_lambda': 0.008835065111635149}. Best is trial 1 with value: 399.6834283441215.

Best trial: 1. Best value: 399.683:  10%|█         | 4/40 [00:29<04:47,  7.99s/it]

[I 2026-08-17 19:22:24,750] Trial 3 finished with value: 403.2559678280731 and parameters: {'n_estimators': 341, 'learning_rate': 0.08278751572307891, 'num_leaves': 120, 'max_depth': 8, 'min_child_samples': 84, 'subsample': 0.701008805685001, 'colsample_bytree': 0.8671410559951771, 'reg_alpha': 5.500556880711675, 'reg_lambda': 0.001058523651187683}. Best is trial 1 with value: 399.6834283441215.

Best trial: 4. Best value: 395.869:  12%|█▎        | 5/40 [00:43<05:58, 10.23s/it]

[I 2026-08-17 19:22:38,953] Trial 4 finished with value: 395.8693410733186 and parameters: {'n_estimators': 583, 'learning_rate': 0.02862368179035823, 'num_leaves': 121, 'max_depth': 7, 'min_child_samples': 53, 'subsample': 0.9159150170183141, 'colsample_bytree': 0.8106077674219349, 'reg_alpha': 0.017078634755083453, 'reg_lambda': 0.08790280750759132}. Best is trial 4 with value: 395.8693410733186.

Best trial: 4. Best value: 395.869:  15%|█▌        | 6/40 [00:48<04:47,  8.45s/it]

[I 2026-08-17 19:22:43,944] Trial 5 finished with value: 399.61382337323016 and parameters: {'n_estimators': 470, 'learning_rate': 0.07544249922487238, 'num_leaves': 19, 'max_depth': 4, 'min_child_samples': 54, 'subsample': 0.8464692964141295, 'colsample_bytree': 0.8375694442257768, 'reg_alpha': 0.7854887279066558, 'reg_lambda': 0.09868727165390863}. Best is trial 4 with value: 395.8693410733186.

Best trial: 6. Best value: 395.347:  18%|█▊        | 7/40 [00:54<04:04,  7.42s/it]

[I 2026-08-17 19:22:49,227] Trial 6 finished with value: 395.3473740016507 and parameters: {'n_estimators': 237, 'learning_rate': 0.07594170006500327, 'num_leaves': 102, 'max_depth': 6, 'min_child_samples': 66, 'subsample': 0.672192198222838, 'colsample_bytree': 0.6237804785377036, 'reg_alpha': 0.057567412232107824, 'reg_lambda': 7.249402444064865}. Best is trial 6 with value: 395.3473740016507.

Best trial: 6. Best value: 395.347:  20%|██        | 8/40 [01:02<04:09,  7.80s/it]

[I 2026-08-17 19:22:57,840] Trial 7 finished with value: 400.84470991699806 and parameters: {'n_estimators': 513, 'learning_rate': 0.05946367907019762, 'num_leaves': 85, 'max_depth': 6, 'min_child_samples': 82, 'subsample': 0.9145260548878367, 'colsample_bytree': 0.9205803973017336, 'reg_alpha': 6.861813733248698, 'reg_lambda': 0.4752063360136251}. Best is trial 6 with value: 395.3473740016507.

Best trial: 6. Best value: 395.347:  22%|██▎       | 9/40 [01:09<03:52,  7.50s/it]

[I 2026-08-17 19:23:04,680] Trial 8 finished with value: 400.01342817954566 and parameters: {'n_estimators': 748, 'learning_rate': 0.06397063542388372, 'num_leaves': 95, 'max_depth': 3, 'min_child_samples': 98, 'subsample': 0.736650231415217, 'colsample_bytree': 0.7874290949261652, 'reg_alpha': 0.11108361804689956, 'reg_lambda': 2.229011180961805}. Best is trial 6 with value: 395.3473740016507.

Best trial: 6. Best value: 395.347:  25%|██▌       | 10/40 [01:16<03:40,  7.34s/it]

[I 2026-08-17 19:23:11,672] Trial 9 finished with value: 399.83359996672715 and parameters: {'n_estimators': 461, 'learning_rate': 0.07220950110271636, 'num_leaves': 21, 'max_depth': 10, 'min_child_samples': 75, 'subsample': 0.7408619079315012, 'colsample_bytree': 0.9013065283187988, 'reg_alpha': 3.521890168266762, 'reg_lambda': 1.610245171426545}. Best is trial 6 with value: 395.3473740016507.

Best trial: 6. Best value: 395.347:  28%|██▊       | 11/40 [01:21<03:09,  6.54s/it]

[I 2026-08-17 19:23:16,411] Trial 10 finished with value: 548.1576104945043 and parameters: {'n_estimators': 233, 'learning_rate': 0.011373200626650565, 'num_leaves': 98, 'max_depth': 5, 'min_child_samples': 13, 'subsample': 0.6069993322549897, 'colsample_bytree': 0.623923631595689, 'reg_alpha': 0.0010159627865379346, 'reg_lambda': 9.151985323561844}. Best is trial 6 with value: 395.3473740016507.

Best trial: 11. Best value: 394.282:  30%|███       | 12/40 [01:37<04:27,  9.54s/it]

[I 2026-08-17 19:23:32,792] Trial 11 finished with value: 394.28167349149726 and parameters: {'n_estimators': 647, 'learning_rate': 0.033743929791361815, 'num_leaves': 127, 'max_depth': 7, 'min_child_samples': 42, 'subsample': 0.8291815342087535, 'colsample_bytree': 0.6316834794843689, 'reg_alpha': 0.04965199562783966, 'reg_lambda': 0.05086001152534828}. Best is trial 11 with value: 394.28167349149726.

Best trial: 11. Best value: 394.282:  32%|███▎      | 13/40 [01:52<04:59, 11.07s/it]

[I 2026-08-17 19:23:47,406] Trial 12 finished with value: 413.34365487778956 and parameters: {'n_estimators': 799, 'learning_rate': 0.1423465140508174, 'num_leaves': 128, 'max_depth': 6, 'min_child_samples': 34, 'subsample': 0.8164971717263465, 'colsample_bytree': 0.6422795101730118, 'reg_alpha': 0.16635876242532158, 'reg_lambda': 0.016330543900618263}. Best is trial 11 with value: 394.28167349149726.

Best trial: 11. Best value: 394.282:  35%|███▌      | 14/40 [02:11<05:47, 13.38s/it]

[I 2026-08-17 19:24:06,099] Trial 13 finished with value: 396.2922545961155 and parameters: {'n_estimators': 645, 'learning_rate': 0.04082122314458364, 'num_leaves': 106, 'max_depth': 9, 'min_child_samples': 37, 'subsample': 0.9901632757061875, 'colsample_bytree': 0.6915908296231077, 'reg_alpha': 0.06626930486975031, 'reg_lambda': 0.001179843111593661}. Best is trial 11 with value: 394.28167349149726.

Best trial: 11. Best value: 394.282:  38%|███▊      | 15/40 [02:16<04:33, 10.95s/it]

[I 2026-08-17 19:24:11,436] Trial 14 finished with value: 448.6824337189776 and parameters: {'n_estimators': 254, 'learning_rate': 0.0154051131936087, 'num_leaves': 109, 'max_depth': 6, 'min_child_samples': 38, 'subsample': 0.6402237592318115, 'colsample_bytree': 0.9988811343879127, 'reg_alpha': 0.0015125614712876837, 'reg_lambda': 0.04537473095419491}. Best is trial 11 with value: 394.28167349149726.

Best trial: 11. Best value: 394.282:  40%|████      | 16/40 [02:28<04:33, 11.39s/it]

[I 2026-08-17 19:24:23,843] Trial 15 finished with value: 409.7277612663773 and parameters: {'n_estimators': 665, 'learning_rate': 0.13955049108821613, 'num_leaves': 82, 'max_depth': 7, 'min_child_samples': 53, 'subsample': 0.8131924797518258, 'colsample_bytree': 0.6002900059280049, 'reg_alpha': 0.483379556790675, 'reg_lambda': 9.934730021794632}. Best is trial 11 with value: 394.28167349149726.

Best trial: 11. Best value: 394.282:  42%|████▎     | 17/40 [02:31<03:24,  8.87s/it]

[I 2026-08-17 19:24:26,855] Trial 16 finished with value: 410.3486034326131 and parameters: {'n_estimators': 203, 'learning_rate': 0.04783143783885721, 'num_leaves': 111, 'max_depth': 5, 'min_child_samples': 65, 'subsample': 0.7797476001468533, 'colsample_bytree': 0.6887442719470215, 'reg_alpha': 0.004553291147857405, 'reg_lambda': 0.004810299129760382}. Best is trial 11 with value: 394.28167349149726.

Best trial: 11. Best value: 394.282:  45%|████▌     | 18/40 [02:46<03:51, 10.54s/it]

[I 2026-08-17 19:24:41,263] Trial 17 finished with value: 394.49970004189004 and parameters: {'n_estimators': 585, 'learning_rate': 0.01822761744740735, 'num_leaves': 70, 'max_depth': 7, 'min_child_samples': 26, 'subsample': 0.644055409832617, 'colsample_bytree': 0.6726793608773141, 'reg_alpha': 0.04459181220344202, 'reg_lambda': 0.3645020817144525}. Best is trial 11 with value: 394.28167349149726.

Best trial: 18. Best value: 393.397:  48%|████▊     | 19/40 [03:00<04:04, 11.65s/it]

[I 2026-08-17 19:24:55,522] Trial 18 finished with value: 393.39654369351945 and parameters: {'n_estimators': 575, 'learning_rate': 0.01923763483606099, 'num_leaves': 59, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.8657022684783133, 'colsample_bytree': 0.6856937171575082, 'reg_alpha': 0.48634028236068255, 'reg_lambda': 0.26183039447986073}. Best is trial 18 with value: 393.39654369351945.

Best trial: 18. Best value: 393.397:  50%|█████     | 20/40 [03:14<04:07, 12.39s/it]

[I 2026-08-17 19:25:09,623] Trial 19 finished with value: 395.3278038936893 and parameters: {'n_estimators': 683, 'learning_rate': 0.019342953752336627, 'num_leaves': 39, 'max_depth': 10, 'min_child_samples': 6, 'subsample': 0.8672599734808728, 'colsample_bytree': 0.7338942053250195, 'reg_alpha': 1.1257129741917038, 'reg_lambda': 0.18130267462859595}. Best is trial 18 with value: 393.39654369351945.

Best trial: 18. Best value: 393.397:  52%|█████▎    | 21/40 [03:29<04:10, 13.19s/it]

[I 2026-08-17 19:25:24,691] Trial 20 finished with value: 402.91501032778734 and parameters: {'n_estimators': 573, 'learning_rate': 0.01062297912703874, 'num_leaves': 52, 'max_depth': 9, 'min_child_samples': 25, 'subsample': 0.8793654451923825, 'colsample_bytree': 0.728204045358165, 'reg_alpha': 0.2271737916199516, 'reg_lambda': 0.028986213702362144}. Best is trial 18 with value: 393.39654369351945.

Best trial: 18. Best value: 393.397:  55%|█████▌    | 22/40 [03:45<04:11, 13.95s/it]

[I 2026-08-17 19:25:40,420] Trial 21 finished with value: 393.44904055969903 and parameters: {'n_estimators': 601, 'learning_rate': 0.017886837555290372, 'num_leaves': 68, 'max_depth': 8, 'min_child_samples': 26, 'subsample': 0.9958074888526929, 'colsample_bytree': 0.6745836787044127, 'reg_alpha': 0.02262455500868621, 'reg_lambda': 0.34015411576392096}. Best is trial 18 with value: 393.39654369351945.

Best trial: 22. Best value: 392.791:  57%|█████▊    | 23/40 [04:02<04:13, 14.91s/it]

[I 2026-08-17 19:25:57,560] Trial 22 finished with value: 392.7906406103766 and parameters: {'n_estimators': 720, 'learning_rate': 0.021890486540699156, 'num_leaves': 61, 'max_depth': 8, 'min_child_samples': 44, 'subsample': 0.9977195268945942, 'colsample_bytree': 0.6804884550350622, 'reg_alpha': 0.00604462842951886, 'reg_lambda': 0.17897155594778247}. Best is trial 22 with value: 392.7906406103766.

Best trial: 23. Best value: 392.025:  60%|██████    | 24/40 [04:20<04:14, 15.93s/it]

[I 2026-08-17 19:26:15,866] Trial 23 finished with value: 392.0253794292889 and parameters: {'n_estimators': 727, 'learning_rate': 0.020946946982452228, 'num_leaves': 64, 'max_depth': 8, 'min_child_samples': 5, 'subsample': 0.9993120791216275, 'colsample_bytree': 0.6668876510405817, 'reg_alpha': 0.004250460179853606, 'reg_lambda': 0.17507431656418232}. Best is trial 23 with value: 392.0253794292889.

Best trial: 23. Best value: 392.025:  62%|██████▎   | 25/40 [04:37<04:02, 16.18s/it]

[I 2026-08-17 19:26:32,617] Trial 24 finished with value: 393.81585105752333 and parameters: {'n_estimators': 746, 'learning_rate': 0.02363961182029363, 'num_leaves': 57, 'max_depth': 9, 'min_child_samples': 7, 'subsample': 0.9594123835642003, 'colsample_bytree': 0.7599451869823952, 'reg_alpha': 0.004245195419222429, 'reg_lambda': 0.1353554612456677}. Best is trial 23 with value: 392.0253794292889.

Best trial: 23. Best value: 392.025:  65%|██████▌   | 26/40 [04:52<03:41, 15.80s/it]

[I 2026-08-17 19:26:47,535] Trial 25 finished with value: 394.38169165787 and parameters: {'n_estimators': 730, 'learning_rate': 0.013818187058617778, 'num_leaves': 42, 'max_depth': 8, 'min_child_samples': 17, 'subsample': 0.9606967436573631, 'colsample_bytree': 0.7087339011602969, 'reg_alpha': 0.004499941720377415, 'reg_lambda': 0.7674858410312099}. Best is trial 23 with value: 392.0253794292889.

Best trial: 23. Best value: 392.025:  68%|██████▊   | 27/40 [05:12<03:41, 17.05s/it]

[I 2026-08-17 19:27:07,522] Trial 26 finished with value: 392.7279462261257 and parameters: {'n_estimators': 704, 'learning_rate': 0.02128923746297542, 'num_leaves': 80, 'max_depth': 9, 'min_child_samples': 5, 'subsample': 0.9523677014448212, 'colsample_bytree': 0.651535212043312, 'reg_alpha': 0.0028955947099663236, 'reg_lambda': 0.2035584951356484}. Best is trial 23 with value: 392.0253794292889.

Best trial: 23. Best value: 392.025:  70%|███████   | 28/40 [05:32<03:35, 17.96s/it]

[I 2026-08-17 19:27:27,599] Trial 27 finished with value: 392.8731593109935 and parameters: {'n_estimators': 711, 'learning_rate': 0.02378490740180304, 'num_leaves': 83, 'max_depth': 9, 'min_child_samples': 14, 'subsample': 0.9751891341868256, 'colsample_bytree': 0.6510101274212864, 'reg_alpha': 0.0023040406445507763, 'reg_lambda': 0.963573665208389}. Best is trial 23 with value: 392.0253794292889.

Best trial: 28. Best value: 391.857:  72%|███████▎  | 29/40 [05:52<03:24, 18.61s/it]

[I 2026-08-17 19:27:47,706] Trial 28 finished with value: 391.85745347905765 and parameters: {'n_estimators': 795, 'learning_rate': 0.03822777950728743, 'num_leaves': 76, 'max_depth': 10, 'min_child_samples': 46, 'subsample': 0.9497299266659393, 'colsample_bytree': 0.6001426885325708, 'reg_alpha': 0.006842629954826702, 'reg_lambda': 0.057143473355586644}. Best is trial 28 with value: 391.85745347905765.

Best trial: 28. Best value: 391.857:  75%|███████▌  | 30/40 [06:13<03:11, 19.17s/it]

[I 2026-08-17 19:28:08,199] Trial 29 finished with value: 392.7118723167538 and parameters: {'n_estimators': 790, 'learning_rate': 0.03481109444486929, 'num_leaves': 77, 'max_depth': 10, 'min_child_samples': 23, 'subsample': 0.9431533147686386, 'colsample_bytree': 0.6070992159177092, 'reg_alpha': 0.00847416843112536, 'reg_lambda': 0.01762145825764413}. Best is trial 28 with value: 391.85745347905765.

Best trial: 28. Best value: 391.857:  78%|███████▊  | 31/40 [06:34<02:59, 19.91s/it]

[I 2026-08-17 19:28:29,837] Trial 30 finished with value: 393.49179536202917 and parameters: {'n_estimators': 783, 'learning_rate': 0.037350426224352515, 'num_leaves': 90, 'max_depth': 10, 'min_child_samples': 21, 'subsample': 0.9405742603191863, 'colsample_bytree': 0.6003620584266296, 'reg_alpha': 0.00885337769564356, 'reg_lambda': 0.0034030607740935877}. Best is trial 28 with value: 391.85745347905765.

Best trial: 28. Best value: 391.857:  80%|████████  | 32/40 [06:54<02:38, 19.83s/it]

[I 2026-08-17 19:28:49,486] Trial 31 finished with value: 396.20109108732896 and parameters: {'n_estimators': 771, 'learning_rate': 0.04302542281868742, 'num_leaves': 76, 'max_depth': 10, 'min_child_samples': 11, 'subsample': 0.9032479325906737, 'colsample_bytree': 0.6537400991897357, 'reg_alpha': 0.008552383035267097, 'reg_lambda': 0.018913455377662147}. Best is trial 28 with value: 391.85745347905765.

Best trial: 28. Best value: 391.857:  82%|████████▎ | 33/40 [07:14<02:19, 19.96s/it]

[I 2026-08-17 19:29:09,753] Trial 32 finished with value: 391.8998000171357 and parameters: {'n_estimators': 696, 'learning_rate': 0.03235243031671072, 'num_leaves': 76, 'max_depth': 9, 'min_child_samples': 20, 'subsample': 0.9590934391892879, 'colsample_bytree': 0.6027434589318136, 'reg_alpha': 0.002099006123165794, 'reg_lambda': 0.060036893924560575}. Best is trial 28 with value: 391.85745347905765.

Best trial: 28. Best value: 391.857:  85%|████████▌ | 34/40 [07:33<01:56, 19.47s/it]

[I 2026-08-17 19:29:28,058] Trial 33 finished with value: 394.7926175100428 and parameters: {'n_estimators': 765, 'learning_rate': 0.05176806811899391, 'num_leaves': 74, 'max_depth': 10, 'min_child_samples': 33, 'subsample': 0.8991920700257102, 'colsample_bytree': 0.6108422955177718, 'reg_alpha': 0.009946773125468501, 'reg_lambda': 0.05950860838559812}. Best is trial 28 with value: 391.85745347905765.

Best trial: 28. Best value: 391.857:  88%|████████▊ | 35/40 [07:50<01:34, 18.93s/it]

[I 2026-08-17 19:29:45,737] Trial 34 finished with value: 394.11183356156056 and parameters: {'n_estimators': 687, 'learning_rate': 0.03227992648325009, 'num_leaves': 67, 'max_depth': 9, 'min_child_samples': 19, 'subsample': 0.932166555008832, 'colsample_bytree': 0.6250569724678922, 'reg_alpha': 0.002082313117928167, 'reg_lambda': 0.008047944143811362}. Best is trial 28 with value: 391.85745347905765.

Best trial: 35. Best value: 391.249:  90%|█████████ | 36/40 [08:05<01:11, 17.77s/it]

[I 2026-08-17 19:30:00,814] Trial 35 finished with value: 391.2488328606593 and parameters: {'n_estimators': 630, 'learning_rate': 0.02887953276027072, 'num_leaves': 50, 'max_depth': 10, 'min_child_samples': 31, 'subsample': 0.9710335525420708, 'colsample_bytree': 0.6573309082922579, 'reg_alpha': 0.02713734692286539, 'reg_lambda': 0.023682550912255268}. Best is trial 35 with value: 391.2488328606593.

Best trial: 35. Best value: 391.249:  92%|█████████▎| 37/40 [08:19<00:50, 16.67s/it]

[I 2026-08-17 19:30:14,916] Trial 36 finished with value: 392.69395527193893 and parameters: {'n_estimators': 621, 'learning_rate': 0.026622066189079377, 'num_leaves': 51, 'max_depth': 9, 'min_child_samples': 49, 'subsample': 0.97172805423696, 'colsample_bytree': 0.7142677015809562, 'reg_alpha': 0.027351647085372327, 'reg_lambda': 0.03377004632127673}. Best is trial 35 with value: 391.2488328606593.

Best trial: 35. Best value: 391.249:  95%|█████████▌| 38/40 [08:31<00:30, 15.07s/it]

[I 2026-08-17 19:30:26,239] Trial 37 finished with value: 394.3914319426733 and parameters: {'n_estimators': 625, 'learning_rate': 0.028372247892011, 'num_leaves': 26, 'max_depth': 10, 'min_child_samples': 31, 'subsample': 0.9734591785831943, 'colsample_bytree': 0.6637483195410976, 'reg_alpha': 0.014180665214188511, 'reg_lambda': 0.08626539374336227}. Best is trial 35 with value: 391.2488328606593.

Best trial: 35. Best value: 391.249:  98%|█████████▊| 39/40 [08:40<00:13, 13.40s/it]

[I 2026-08-17 19:30:35,748] Trial 38 finished with value: 405.62718531330734 and parameters: {'n_estimators': 527, 'learning_rate': 0.10544632522949356, 'num_leaves': 44, 'max_depth': 9, 'min_child_samples': 29, 'subsample': 0.8914326466496507, 'colsample_bytree': 0.7629225459514788, 'reg_alpha': 0.0010300271704405466, 'reg_lambda': 0.009251806230231908}. Best is trial 35 with value: 391.2488328606593.

Best trial: 35. Best value: 391.249: 100%|██████████| 40/40 [08:56<00:00, 13.41s/it]
[I 2026-08-17 19:30:51,213] A new study created in memory with name: catboost_v3_tuning

[I 2026-08-17 19:30:51,210] Trial 39 finished with value: 395.0222565153235 and parameters: {'n_estimators': 674, 'learning_rate': 0.047458234991600984, 'num_leaves': 64, 'max_depth': 8, 'min_child_samples': 60, 'subsample': 0.9238477463973226, 'colsample_bytree': 0.6399391159738962, 'reg_alpha': 0.014739542558368202, 'reg_lambda': 0.08314948728385993}. Best is trial 35 with value: 391.2488328606593.
Best lgbm OOF RMSE: 391.25  (default-params baseline: 399.46)
{'n_estimators': 630, 'learning_rate': 0.02887953276027072, 'num_leaves': 50, 'max_depth': 10, 'min_child_samples': 31, 'subsample': 0.9710335525420708, 'colsample_bytree': 0.6573309082922579, 'reg_alpha': 0.02713734692286539, 'reg_lambda': 0.023682550912255268}

Best trial: 0. Best value: 407.311:   2%|▎         | 1/40 [00:18<11:46, 18.12s/it]

[I 2026-08-17 19:31:09,332] Trial 0 finished with value: 407.310651872783 and parameters: {'iterations': 655, 'learning_rate': 0.12057203339676464, 'depth': 8, 'l2_leaf_reg': 8.91022185346317, 'bagging_temperature': 0.6572045577041534, 'random_strength': 0.9906375011822965, 'border_count': 49}. Best is trial 0 with value: 407.310651872783.

Best trial: 1. Best value: 394.363:   5%|▌         | 2/40 [00:36<11:27, 18.10s/it]

[I 2026-08-17 19:31:27,418] Trial 1 finished with value: 394.36265168724094 and parameters: {'iterations': 486, 'learning_rate': 0.09092794509847488, 'depth': 8, 'l2_leaf_reg': 0.22025339430512578, 'bagging_temperature': 0.9471936050728899, 'random_strength': 0.0027232463855378993, 'border_count': 254}. Best is trial 1 with value: 394.36265168724094.

Best trial: 1. Best value: 394.363:   8%|▊         | 3/40 [00:41<07:25, 12.03s/it]

[I 2026-08-17 19:31:32,228] Trial 2 finished with value: 516.1533587822313 and parameters: {'iterations': 280, 'learning_rate': 0.018994061805867882, 'depth': 4, 'l2_leaf_reg': 1.466755940635608, 'bagging_temperature': 0.5407892562795419, 'random_strength': 0.21299484819318362, 'border_count': 199}. Best is trial 1 with value: 394.36265168724094.

Best trial: 1. Best value: 394.363:  10%|█         | 4/40 [00:47<05:52,  9.80s/it]

[I 2026-08-17 19:31:38,619] Trial 3 finished with value: 422.2166637695466 and parameters: {'iterations': 292, 'learning_rate': 0.03402042993995306, 'depth': 6, 'l2_leaf_reg': 0.012420020153359721, 'bagging_temperature': 0.29759572332877426, 'random_strength': 0.04782253631064464, 'border_count': 186}. Best is trial 1 with value: 394.36265168724094.

Best trial: 4. Best value: 391.671:  12%|█▎        | 5/40 [01:00<06:22, 10.94s/it]

[I 2026-08-17 19:31:51,576] Trial 4 finished with value: 391.67106296196494 and parameters: {'iterations': 704, 'learning_rate': 0.04995902871453623, 'depth': 5, 'l2_leaf_reg': 0.03226060844012155, 'bagging_temperature': 0.27404475454193755, 'random_strength': 2.029146523434697, 'border_count': 212}. Best is trial 4 with value: 391.67106296196494.

Best trial: 4. Best value: 391.671:  15%|█▌        | 6/40 [01:07<05:26,  9.60s/it]

[I 2026-08-17 19:31:58,586] Trial 5 finished with value: 537.762996567524 and parameters: {'iterations': 444, 'learning_rate': 0.013621550374776215, 'depth': 3, 'l2_leaf_reg': 0.04097060940670334, 'bagging_temperature': 0.9619945385301119, 'random_strength': 0.012332448572457164, 'border_count': 164}. Best is trial 4 with value: 391.67106296196494.

Best trial: 4. Best value: 391.671:  18%|█▊        | 7/40 [01:23<06:32, 11.89s/it]

[I 2026-08-17 19:32:15,176] Trial 6 finished with value: 403.704755266166 and parameters: {'iterations': 530, 'learning_rate': 0.14524738610727633, 'depth': 8, 'l2_leaf_reg': 1.2093539481834321, 'bagging_temperature': 0.20945705127745118, 'random_strength': 2.1190273382154508, 'border_count': 175}. Best is trial 4 with value: 391.67106296196494.

Best trial: 7. Best value: 390.73:  20%|██        | 8/40 [01:39<06:55, 12.97s/it]

[I 2026-08-17 19:32:30,459] Trial 7 finished with value: 390.72971822015563 and parameters: {'iterations': 676, 'learning_rate': 0.08320111503548189, 'depth': 6, 'l2_leaf_reg': 6.8209985296769915, 'bagging_temperature': 0.8788366182612638, 'random_strength': 0.0037719835225441217, 'border_count': 244}. Best is trial 7 with value: 390.72971822015563.

Best trial: 7. Best value: 390.73:  22%|██▎       | 9/40 [01:46<05:44, 11.10s/it]

[I 2026-08-17 19:32:37,451] Trial 8 finished with value: 463.716420575811 and parameters: {'iterations': 417, 'learning_rate': 0.027153225434325128, 'depth': 4, 'l2_leaf_reg': 5.13711642181023, 'bagging_temperature': 0.6073336789791021, 'random_strength': 6.389925392277106, 'border_count': 172}. Best is trial 7 with value: 390.72971822015563.

Best trial: 7. Best value: 390.73:  25%|██▌       | 10/40 [01:58<05:43, 11.46s/it]

[I 2026-08-17 19:32:49,720] Trial 9 finished with value: 396.56665293407605 and parameters: {'iterations': 594, 'learning_rate': 0.10091679035352076, 'depth': 6, 'l2_leaf_reg': 0.10611095378778417, 'bagging_temperature': 0.4403778369620934, 'random_strength': 0.009970138581670127, 'border_count': 82}. Best is trial 7 with value: 390.72971822015563.

Best trial: 7. Best value: 390.73:  28%|██▊       | 11/40 [02:52<11:46, 24.36s/it]

[I 2026-08-17 19:33:43,337] Trial 10 finished with value: 409.9214187093909 and parameters: {'iterations': 790, 'learning_rate': 0.010434998596771416, 'depth': 10, 'l2_leaf_reg': 0.5565958644625434, 'bagging_temperature': 0.06854522448121747, 'random_strength': 0.0012089888981757192, 'border_count': 116}. Best is trial 7 with value: 390.72971822015563.

Best trial: 7. Best value: 390.73:  30%|███       | 12/40 [03:08<10:16, 22.03s/it]

[I 2026-08-17 19:34:00,025] Trial 11 finished with value: 392.45542926312226 and parameters: {'iterations': 734, 'learning_rate': 0.058591905255396204, 'depth': 6, 'l2_leaf_reg': 0.014281036164000338, 'bagging_temperature': 0.805078711486916, 'random_strength': 0.15816346364204406, 'border_count': 244}. Best is trial 7 with value: 390.72971822015563.

Best trial: 7. Best value: 390.73:  32%|███▎      | 13/40 [03:21<08:40, 19.26s/it]

[I 2026-08-17 19:34:12,916] Trial 12 finished with value: 394.55949024964116 and parameters: {'iterations': 668, 'learning_rate': 0.05206149083781253, 'depth': 5, 'l2_leaf_reg': 0.07259477042485166, 'bagging_temperature': 0.046856328041978895, 'random_strength': 0.47533163990549043, 'border_count': 219}. Best is trial 7 with value: 390.72971822015563.

Best trial: 13. Best value: 389.947:  35%|███▌      | 14/40 [03:40<08:15, 19.05s/it]

[I 2026-08-17 19:34:31,464] Trial 13 finished with value: 389.946912797372 and parameters: {'iterations': 706, 'learning_rate': 0.063236168484434, 'depth': 7, 'l2_leaf_reg': 3.3271047707901125, 'bagging_temperature': 0.3617419092754119, 'random_strength': 7.5179518092982835, 'border_count': 227}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  38%|███▊      | 15/40 [03:57<07:40, 18.41s/it]

[I 2026-08-17 19:34:48,389] Trial 14 finished with value: 392.30189763017194 and parameters: {'iterations': 610, 'learning_rate': 0.07578333674207782, 'depth': 7, 'l2_leaf_reg': 3.4523175430516444, 'bagging_temperature': 0.7370320010618943, 'random_strength': 9.307907325154995, 'border_count': 227}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  40%|████      | 16/40 [04:57<12:21, 30.90s/it]

[I 2026-08-17 19:35:48,305] Trial 15 finished with value: 395.94227103555244 and parameters: {'iterations': 794, 'learning_rate': 0.03626822108097728, 'depth': 10, 'l2_leaf_reg': 2.377593969975508, 'bagging_temperature': 0.42012113046057387, 'random_strength': 0.05156312835743898, 'border_count': 139}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  42%|████▎     | 17/40 [05:13<10:11, 26.57s/it]

[I 2026-08-17 19:36:04,794] Trial 16 finished with value: 392.53823614903536 and parameters: {'iterations': 581, 'learning_rate': 0.06606560572536027, 'depth': 7, 'l2_leaf_reg': 7.776942162430005, 'bagging_temperature': 0.8071829941352457, 'random_strength': 0.008237895357323157, 'border_count': 253}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  45%|████▌     | 18/40 [05:50<10:54, 29.73s/it]

[I 2026-08-17 19:36:41,892] Trial 17 finished with value: 392.7116925350636 and parameters: {'iterations': 731, 'learning_rate': 0.044093430725973486, 'depth': 9, 'l2_leaf_reg': 0.5607649943853166, 'bagging_temperature': 0.4657881262256336, 'random_strength': 0.03680835854305484, 'border_count': 223}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  48%|████▊     | 19/40 [06:00<08:17, 23.69s/it]

[I 2026-08-17 19:36:51,513] Trial 18 finished with value: 414.68508268843226 and parameters: {'iterations': 386, 'learning_rate': 0.02550245166748153, 'depth': 7, 'l2_leaf_reg': 1.808599269800556, 'bagging_temperature': 0.1956353158147069, 'random_strength': 0.16480970222498048, 'border_count': 143}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  50%|█████     | 20/40 [06:10<06:32, 19.60s/it]

[I 2026-08-17 19:37:01,591] Trial 19 finished with value: 392.8244100855373 and parameters: {'iterations': 537, 'learning_rate': 0.08027794143331703, 'depth': 5, 'l2_leaf_reg': 0.5963200480972713, 'bagging_temperature': 0.887339421301458, 'random_strength': 0.0010054157331365833, 'border_count': 203}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  52%|█████▎    | 21/40 [06:45<07:39, 24.21s/it]

[I 2026-08-17 19:37:36,528] Trial 20 finished with value: 407.3343092772116 and parameters: {'iterations': 675, 'learning_rate': 0.14363195803479162, 'depth': 9, 'l2_leaf_reg': 4.144129841322827, 'bagging_temperature': 0.6982411675635203, 'random_strength': 0.0029910954279588446, 'border_count': 235}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  55%|█████▌    | 22/40 [06:58<06:17, 20.96s/it]

[I 2026-08-17 19:37:49,925] Trial 21 finished with value: 391.13501288480916 and parameters: {'iterations': 723, 'learning_rate': 0.04843653333324239, 'depth': 5, 'l2_leaf_reg': 0.2330817327540828, 'bagging_temperature': 0.26941002199426267, 'random_strength': 3.3572726679767455, 'border_count': 209}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  57%|█████▊    | 23/40 [07:15<05:35, 19.72s/it]

[I 2026-08-17 19:38:06,756] Trial 22 finished with value: 390.21984937191485 and parameters: {'iterations': 750, 'learning_rate': 0.06835275962534913, 'depth': 6, 'l2_leaf_reg': 0.1710589327806649, 'bagging_temperature': 0.31422191796739457, 'random_strength': 3.9807792550541663, 'border_count': 193}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  60%|██████    | 24/40 [07:29<04:48, 18.02s/it]

[I 2026-08-17 19:38:20,819] Trial 23 finished with value: 392.6981024930028 and parameters: {'iterations': 632, 'learning_rate': 0.10297431168316619, 'depth': 6, 'l2_leaf_reg': 0.9042782555272488, 'bagging_temperature': 0.35989282045543525, 'random_strength': 0.8156043786111946, 'border_count': 189}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  62%|██████▎   | 25/40 [07:50<04:43, 18.89s/it]

[I 2026-08-17 19:38:41,738] Trial 24 finished with value: 390.3508953491743 and parameters: {'iterations': 771, 'learning_rate': 0.06475113904917486, 'depth': 7, 'l2_leaf_reg': 0.2583187061658169, 'bagging_temperature': 0.11912760468429057, 'random_strength': 4.324598589943408, 'border_count': 229}. Best is trial 13 with value: 389.946912797372.

Best trial: 13. Best value: 389.947:  65%|██████▌   | 26/40 [08:10<04:28, 19.16s/it]

[I 2026-08-17 19:39:01,530] Trial 25 finished with value: 392.30040237917893 and parameters: {'iterations': 764, 'learning_rate': 0.07170437206922545, 'depth': 7, 'l2_leaf_reg': 0.20963994090002708, 'bagging_temperature': 0.13650912815942806, 'random_strength': 4.310097038003629, 'border_count': 156}. Best is trial 13 with value: 389.946912797372.

Best trial: 26. Best value: 388.385:  68%|██████▊   | 27/40 [08:36<04:35, 21.19s/it]

[I 2026-08-17 19:39:27,436] Trial 26 finished with value: 388.38513666509584 and parameters: {'iterations': 762, 'learning_rate': 0.03849150674768317, 'depth': 8, 'l2_leaf_reg': 0.12953479098770296, 'bagging_temperature': 0.13123775849409716, 'random_strength': 1.7290255652254807, 'border_count': 191}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  70%|███████   | 28/40 [09:05<04:44, 23.72s/it]

[I 2026-08-17 19:39:57,067] Trial 27 finished with value: 389.5496424811486 and parameters: {'iterations': 736, 'learning_rate': 0.039078409018024646, 'depth': 9, 'l2_leaf_reg': 0.1075823535879959, 'bagging_temperature': 0.3482250526386882, 'random_strength': 1.459724060909594, 'border_count': 131}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  72%|███████▎  | 29/40 [09:32<04:30, 24.57s/it]

[I 2026-08-17 19:40:23,636] Trial 28 finished with value: 392.70603362394974 and parameters: {'iterations': 698, 'learning_rate': 0.037468136289636494, 'depth': 9, 'l2_leaf_reg': 0.029161128476738078, 'bagging_temperature': 0.015495116438470735, 'random_strength': 1.3005277349223405, 'border_count': 110}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  75%|███████▌  | 30/40 [09:49<03:43, 22.34s/it]

[I 2026-08-17 19:40:40,752] Trial 29 finished with value: 400.0054405354551 and parameters: {'iterations': 638, 'learning_rate': 0.02631438382405514, 'depth': 8, 'l2_leaf_reg': 0.05983348549845788, 'bagging_temperature': 0.5394515310997086, 'random_strength': 0.5802478784644919, 'border_count': 57}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  78%|███████▊  | 31/40 [10:06<03:06, 20.77s/it]

[I 2026-08-17 19:40:57,854] Trial 30 finished with value: 394.69156356808884 and parameters: {'iterations': 569, 'learning_rate': 0.03082416436738966, 'depth': 8, 'l2_leaf_reg': 0.12016101676528147, 'bagging_temperature': 0.20542178511388637, 'random_strength': 0.3519842806757346, 'border_count': 114}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  80%|████████  | 32/40 [10:31<02:55, 21.92s/it]

[I 2026-08-17 19:41:22,475] Trial 31 finished with value: 402.7266163601248 and parameters: {'iterations': 749, 'learning_rate': 0.04332080999922031, 'depth': 9, 'l2_leaf_reg': 0.11823298669582404, 'bagging_temperature': 0.3775348418504438, 'random_strength': 1.6523639478605798, 'border_count': 38}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  82%|████████▎ | 33/40 [10:56<02:39, 22.78s/it]

[I 2026-08-17 19:41:47,241] Trial 32 finished with value: 392.685911601331 and parameters: {'iterations': 798, 'learning_rate': 0.058296281982888, 'depth': 8, 'l2_leaf_reg': 0.3598502717872779, 'bagging_temperature': 0.3402882000776221, 'random_strength': 9.185255158597732, 'border_count': 135}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  85%|████████▌ | 34/40 [11:19<02:18, 23.08s/it]

[I 2026-08-17 19:42:11,034] Trial 33 finished with value: 399.7244148732641 and parameters: {'iterations': 703, 'learning_rate': 0.019839834459069935, 'depth': 8, 'l2_leaf_reg': 0.1554075568731269, 'bagging_temperature': 0.4980624938649915, 'random_strength': 2.84967256052663, 'border_count': 189}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  88%|████████▊ | 35/40 [11:33<01:41, 20.35s/it]

[I 2026-08-17 19:42:25,011] Trial 34 finished with value: 409.8029050743347 and parameters: {'iterations': 210, 'learning_rate': 0.04021525213459198, 'depth': 10, 'l2_leaf_reg': 0.02101261707564111, 'bagging_temperature': 0.3132875905417767, 'random_strength': 0.971348420300083, 'border_count': 91}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  90%|█████████ | 36/40 [12:03<01:32, 23.23s/it]

[I 2026-08-17 19:42:54,958] Trial 35 finished with value: 406.9134378000763 and parameters: {'iterations': 641, 'learning_rate': 0.01990039643100969, 'depth': 9, 'l2_leaf_reg': 0.06374115835401149, 'bagging_temperature': 0.24343043086208935, 'random_strength': 5.84044613222444, 'border_count': 191}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  92%|█████████▎| 37/40 [12:22<01:06, 22.01s/it]

[I 2026-08-17 19:43:14,129] Trial 36 finished with value: 390.11492260655433 and parameters: {'iterations': 745, 'learning_rate': 0.03243198946016674, 'depth': 7, 'l2_leaf_reg': 0.41525150542182776, 'bagging_temperature': 0.12283935242959221, 'random_strength': 2.7966464402161444, 'border_count': 163}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  95%|█████████▌| 38/40 [12:45<00:44, 22.05s/it]

[I 2026-08-17 19:43:36,278] Trial 37 finished with value: 391.323260417073 and parameters: {'iterations': 705, 'learning_rate': 0.031787380069015825, 'depth': 8, 'l2_leaf_reg': 0.42561328814659016, 'bagging_temperature': 0.11387666460970451, 'random_strength': 2.219402397829919, 'border_count': 156}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385:  98%|█████████▊| 39/40 [13:03<00:20, 20.89s/it]

[I 2026-08-17 19:43:54,466] Trial 38 finished with value: 397.7928826298421 and parameters: {'iterations': 683, 'learning_rate': 0.024247096766041816, 'depth': 7, 'l2_leaf_reg': 0.943681163537104, 'bagging_temperature': 0.16490890598552627, 'random_strength': 1.2467050189007922, 'border_count': 174}. Best is trial 26 with value: 388.38513666509584.

Best trial: 26. Best value: 388.385: 100%|██████████| 40/40 [13:28<00:00, 20.22s/it]

[I 2026-08-17 19:44:19,817] Trial 39 finished with value: 390.24336289286754 and parameters: {'iterations': 768, 'learning_rate': 0.03115610130503757, 'depth': 8, 'l2_leaf_reg': 0.047589755780206834, 'bagging_temperature': 0.594748383214619, 'random_strength': 0.7005780653860904, 'border_count': 153}. Best is trial 26 with value: 388.38513666509584.
Best catboost OOF RMSE: 388.39  (default-params baseline: 394.27)
{'iterations': 762, 'learning_rate': 0.03849150674768317, 'depth': 8, 'l2_leaf_reg': 0.12953479098770296, 'bagging_temperature': 0.13123775849409716, 'random_strength': 1.7290255652254807, 'border_count': 191}

## Tuned Model Comparison

In [13]:
tuned_comparison = pd.DataFrame([
    {"model": name, "tuned_oof_rmse": study.best_value}
    for name, study in studies.items()
]).sort_values("tuned_oof_rmse").reset_index(drop=True)
tuned_comparison

      model  tuned_oof_rmse
0  catboost      388.385137
1      lgbm      391.248833
2       xgb      391.658332

## Target-Encoding Check — Holiday Identity

In [14]:
CHAMPION_NAME = tuned_comparison.iloc[0]["model"]
CHAMPION_OOF_RMSE = tuned_comparison.iloc[0]["tuned_oof_rmse"]
CHAMPION_PARAMS = studies[CHAMPION_NAME].best_params

champion_fold_features = features.compose(features.extreme_event_fold_features, features.holiday_freq_fold_features)
champion_model_fn = lambda: hpo.MODEL_BUILDERS[CHAMPION_NAME](CHAMPION_PARAMS)

holiday_oof_rmse = hpo.oof_rmse_for_model(
    train, config.FOLD_BOUNDARIES, config.TARGET, config.FEATURES_V3 + ["holiday_freq"],
    champion_model_fn, champion_fold_features,
)

print(f"Champion ({CHAMPION_NAME}) OOF RMSE without holiday_freq: {CHAMPION_OOF_RMSE:.2f}")
print(f"Champion ({CHAMPION_NAME}) OOF RMSE with holiday_freq:    {holiday_oof_rmse:.2f}")

USE_HOLIDAY_FEATURE = holiday_oof_rmse < CHAMPION_OOF_RMSE
print(f"\nUse holiday_freq in final model: {USE_HOLIDAY_FEATURE}")

Champion (catboost) OOF RMSE without holiday_freq: 388.39
Champion (catboost) OOF RMSE with holiday_freq:    391.37

Use holiday_freq in final model: False

## Champion Selection & Final Model Fit
Same fit/apply feature functions as every CV fold above — only fit on the full `train` set this time instead of a fold slice.

In [15]:
WINNING_FEATURES = config.FEATURES_V3 + ["holiday_freq"] if USE_HOLIDAY_FEATURE else config.FEATURES_V3

thresholds = features.fit_extreme_event_thresholds(train)
train_final = features.apply_extreme_event_features(train, thresholds)
test_final = features.apply_extreme_event_features(test, thresholds)

holiday_freq_map = None
if USE_HOLIDAY_FEATURE:
    holiday_freq_map = features.fit_holiday_freq_map(train_final)
    train_final = features.apply_holiday_freq(train_final, holiday_freq_map)
    test_final = features.apply_holiday_freq(test_final, holiday_freq_map)

X_train_final, y_train_final = train_final[WINNING_FEATURES], train_final[config.TARGET]
X_test_final, y_test_final = test_final[WINNING_FEATURES], test_final[config.TARGET]

trend_model_final = LinearRegression().fit(train_final[["trend_idx"]], y_train_final)
trend_train_final = trend_model_final.predict(train_final[["trend_idx"]])
trend_test_final = trend_model_final.predict(test_final[["trend_idx"]])

residual_target_final = y_train_final - trend_train_final

final_model = hpo.MODEL_BUILDERS[CHAMPION_NAME](CHAMPION_PARAMS)
final_model.fit(X_train_final, residual_target_final)
pred_test_final = trend_test_final + final_model.predict(X_test_final)

test_metrics = cv.compute_metrics(y_test_final.to_numpy(), pred_test_final)

print(f"Champion model: {CHAMPION_NAME}  |  Features: {'v3 + holiday_freq' if USE_HOLIDAY_FEATURE else 'v3'}")
print(f"Final test RMSE: {test_metrics['rmse']:.2f}")
print(f"Final test MAPE: {test_metrics['mape']:.3f}%")
print(f"Final test Peak-MAPE: {test_metrics['peak_mape']:.3f}%")

Champion model: catboost  |  Features: v3
Final test RMSE: 353.48
Final test MAPE: 2.842%
Final test Peak-MAPE: 3.281%

## MLflow Logging — Champion Model

In [16]:
import joblib
from pathlib import Path
import mlflow
import mlflow.pyfunc


class ElectricityForecaster(mlflow.pyfunc.PythonModel):
    def load_context(self, context):
        self.bundle = joblib.load(context.artifacts["model_bundle"])
        self.trend_model = self.bundle["trend_model"]
        self.residual_model = self.bundle["residual_model"]
        self.features = self.bundle["features"]

    def predict(self, context, model_input):
        df = model_input if isinstance(model_input, pd.DataFrame) else pd.DataFrame(model_input)
        trend_preds = self.trend_model.predict(df[["trend_idx"]])
        residual_preds = self.residual_model.predict(df[self.features])
        return trend_preds + residual_preds


artifact_dir = Path("artifacts")
artifact_dir.mkdir(exist_ok=True)
model_path = artifact_dir / "electricity_load_forecaster.pkl"

production_bundle = {
    "trend_model": trend_model_final,
    "residual_model": final_model,
    "features": WINNING_FEATURES,
    "target": config.TARGET,
    "thresholds": thresholds,
    "holiday_freq_map": holiday_freq_map,  # None if USE_HOLIDAY_FEATURE is False
    "model_family": f"trend_plus_tuned_{CHAMPION_NAME}",
    "feature_version": "v3_holiday" if USE_HOLIDAY_FEATURE else "v3",
    "train_end": str(train_final["timestamp"].max()),
    "test_start": str(test_final["timestamp"].min()),
    "trend_idx_origin" : df["timestamp"].min(),
}
joblib.dump(production_bundle, model_path)

with mlflow.start_run(run_name="production_candidate_final"):
    mlflow.log_params({
        "model_family": production_bundle["model_family"],
        "feature_version": production_bundle["feature_version"],
        **{f"{CHAMPION_NAME}_{k}": v for k, v in CHAMPION_PARAMS.items()},
        "train_rows": len(train_final),
        "test_rows": len(test_final),
        "purge_days": config.PURGE_DAYS,
        "train_end": production_bundle["train_end"],
        "test_start": production_bundle["test_start"],
    })
    mlflow.log_metrics({
        "cv_oof_rmse": float(CHAMPION_OOF_RMSE),
        "test_rmse": float(test_metrics["rmse"]),
        "test_mape_pct": float(test_metrics["mape"]),
        "test_peak_mape_pct": float(test_metrics["peak_mape"]),
    })

    mlflow.pyfunc.log_model(
        artifact_path="model",
        python_model=ElectricityForecaster(),
        artifacts={"model_bundle": str(model_path)},
        registered_model_name="Electricity-Load-Forecaster",
    )

print("Successfully logged params, metrics, and registered the production candidate model!")

/teamspace/studios/this_studio/electricity-distribution-forecast/.venv/lib/python3.14/site-packages/mlflow/types/type_hints.py:232: UserWarning: Any type hint is inferred as AnyType, and MLflow doesn't validate the data for this type. Please use a more specific type hint to enable data validation.
  dtype=_infer_colspec_type_from_type_hint(effective_type).dtype,
/teamspace/studios/this_studio/electricity-distribution-forecast/.venv/lib/python3.14/site-packages/mlflow/types/type_hints.py:213: UserWarning: Any type hint is inferred as AnyType, and MLflow doesn't validate the data for this type. Please use a more specific type hint to enable data validation.
  dtype=Map(_infer_colspec_type_from_type_hint(type_hint=args[1]).dtype),
/teamspace/studios/this_studio/electricity-distribution-forecast/.venv/lib/python3.14/site-packages/mlflow/pyfunc/utils/data_validation.py:187: UserWarning: Add type hints to the `predict` method to enable data validation and automatic signature inference during model logging. Check https://mlflow.org/docs/latest/model/python_model.html#type-hint-usage-in-pythonmodel for more details.
  color_warning(
2026/08/17 19:44:54 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/08/17 19:44:55 WARNING mlflow.pyfunc: Passing a Python object as `python_model` causes it to be serialized using CloudPickle, it requires exercising caution as Python object serialization mechanisms may execute arbitrary code during deserialization.Consider using a file path (str or Path) instead. See https://mlflow.org/docs/latest/ml/model/models-from-code/ for details.
Downloading artifacts: 100%|██████████| 1/1 [00:00<00:00, 506.74it/s]
2026/08/17 19:44:58 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
Registered model 'Electricity-Load-Forecaster' already exists. Creating a new version of this model...
2026/08/17 19:45:00 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: Electricity-Load-Forecaster, version 6
Created version '6' of model 'Electricity-Load-Forecaster'.

🏃 View run production_candidate_final at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2/runs/3aff01a37031473ba46b20a3ff759819
🧪 View experiment at: https://dagshub.com/dunnioluajayi/electricity-distribution-forecast.mlflow/#/experiments/2
Successfully logged params, metrics, and registered the production candidate model!

In [17]:
sample = test[fe.RAW_REQUIRED_COLUMNS + ["timestamp"]].sample(20, random_state=42)
sample.to_parquet("../data/interim/pipeline_test_sample.parquet", index=False)

In [19]:
sample.head(5)

,temp_c,humidity_pct,precip_mm,tmax,tmin,tavg,hour,dayofweek,month,is_weekend,is_holiday,holiday_name,load_lag_24,load_lag_168,hour_x_temp,temp_c_roll_std_72,temp_change_vs_lag24,timestamp
4956,24.278595,76.195895,0.306309,25.403766,13.319124,19.960156,11,5,3,1,0,NaN,8969.65,7543.52,267.064544,2.807702,-0.807919,2026-03-07 17:00:00+00:00
1061,22.511417,64.390013,0.000000,32.123985,20.268225,26.934043,5,4,9,0,0,NaN,8182.80,8068.30,112.557083,3.672158,-1.525801,2025-09-26 10:00:00+00:00
5057,25.746177,40.689880,0.000000,27.242737,16.130785,20.875474,17,2,3,0,0,NaN,9516.46,10428.49,437.685004,3.231015,-0.344646,2026-03-11 22:00:00+00:00
222,23.589900,87.376289,0.000000,33.016493,23.064509,27.589314,6,4,8,0,0,NaN,9054.73,9721.99,141.539401,3.623078,-2.002301,2025-08-22 11:00:00+00:00
7517,25.931607,94.081014,0.058639,33.770726,25.729360,29.219887,5,0,6,0,0,NaN,7836.24,8440.21,129.658034,2.521536,2.693734,2026-06-22 10:00:00+00:00

In [18]:
import mlflow
print(mlflow.pyfunc.get_model_dependencies("models:/Electricity-Load-Forecaster@champion"))

Downloading artifacts: 100%|██████████| 6/6 [00:01<00:00,  4.07it/s]
2026/08/17 19:45:03 INFO mlflow.pyfunc: To install the dependencies that were used to train the model, run the following command: '%pip install -r /tmp/tmpxk9mrvdo/requirements.txt'.

/tmp/tmpxk9mrvdo/requirements.txt